#Panel Administrador
admin.btn.descPdf = Baixar PDF
admin.btn.elimUss = Desativar conta

#Panel Codigo de Verificacion
cv.lbl.titulo = Insira o código de verificação enviado para seu e-mail
cv.btn.cerrarSesion = Sair
cv.btn.verificar = Verificar

#Panel Inicio de Sesion
inic.lbl.email = E-mail
inic.lbl.contra = Senha
inic.btn.iniciarSesion = Entrar
inic.btn.registrar = Cadastrar-se

#Panel Registro
reg.lbl.nombre = Nome:
reg.lbl.apellido = Sobrenome:
reg.lbl.alias = Apelido (único e irrepetível):
reg.lbl.email = E-mail:
reg.lbl.fechaNac = Data de Nascimento (DD/MM/AAAA):
reg.lbl.contra = Senha:
reg.lbl.confirContra = Confirmar Senha:
reg.lbl.estatura = Altura (cm):
reg.lbl.ingresosMensuales = Renda Mensal (R$):
reg.chk.divorciada = Você já se divorciou?
reg.btn.registrar = Cadastrar
reg.btn.cancelar = Cancelar

#Panel Genero
gen.lbl.titulo = Cadastrar-se como: 
gen.lbl.hombre = Homem
gen.lbl.mujer = Mulher
gen.btn.volver = Voltar

#Panel Perfil
perfil.lbl.titulo = Perfil
perfil.lbl.fotoPerf = Alterar foto
perfil.lbl.nombre = Nome
perfil.lbl.apellido = Sobrenome
perfil.lbl.alias = Apelido
perfil.lbl.estatura = Altura
perfil.lbl.edadMinima = Idade mínima
perfil.lbl.edadMaxima = Idade máxima
perfil.lbl.visibilidad = Perfil visível para outros usuários
perfil.btn.actualizar = Atualizar
perfil.btn.cancelar = Cancelar
perfil.btn.cerrarSesion = Encerrar sessão

#Panel Perfil Mujer
perfil.lbl.divorcio = É divorciada?
perfil.lbl.estaIdeal = Altura ideal

#Panel Perfil Hombre
perfil.lbl.ingresos = Renda mensal
perfil.lbl.mostrarDivorcio = Mostrar mulheres divorciadas

#Panel Principal Scroll
scroll.lbl.edad = Idade:
scroll.lbl.ingresos = Renda:
scroll.lbl.estatura = Altura:
scroll.lbl.divorciada = É divorciada?
