#Panel Administrador
admin.btn.descPdf = Baixar PDF
admin.btn.elimUss = Desativar conta

#Panel Codigo de Verificacion
cv.lbl.titulo = Insira o código de verificação enviado para seu e-mail
cv.btn.cerrarSesion = Sair
cv.btn.verificar = Verificar

#Panel Inicio de Sesion
inic.lbl.email = E-mail
inic.lbl.contra = Senha
inic.btn.iniciarSesion = Entrar
inic.btn.registrar = Cadastrar-se

#Panel Perfil
perfil.lbl.titulo = Perfil
perfil.lbl.fotoPerf = Foto de Perfil (.jpg)
perfil.lbl.nombre = Nomes
perfil.lbl.apellido = Sobrenomes
perfil.lbl.alias = Apelido
perfil.lbl.estatura = Altura
perfil.lbl.visible = Visibilidade
perfil.lbl.estaIdeal = Altura ideal
perfil.lbl.edadMinima = Idade mínima
perfil.lbl.edadMaxima = Idade máxima
perfil.lbl.ingresos = Renda mensal
perfil.lbl.divorcio = Número de divórcios

#Panel Registro
reg.lbl.nombre = Nome:
reg.lbl.apellido = Sobrenome:
reg.lbl.alias = Apelido (único e irrepetível):
reg.lbl.email = E-mail:
reg.lbl.fechaNac = Data de Nascimento (DD/MM/AAAA):
reg.lbl.contra = Senha:
reg.lbl.confirContra = Confirmar Senha:
reg.lbl.estatura = Altura (cm):
reg.lbl.ingresosMensuales = Renda Mensal (R$):
reg.chk.divorciada = Você já se divorciou?
reg.btn.registrar = Cadastrar
reg.btn.cancelar = Cancelar

#Panel Genero
gen.lbl.titulo = Cadastrar-se como: 
gen.lbl.hombre = Homem
gen.lbl.mujer = Mulher
gen.btn.volver = Voltar