#Painel Administrador
admin.btn.descPdf = Baixar PDF
admin.btn.elimUss = Desativar conta

#Painel Código de Verificação
cv.lbl.titulo = Insira o código de verificação enviado para seu e-mail
cv.btn.cerrarSesion = Sair
cv.btn.verificar = Verificar

#Painel Início de Sessão
inic.lbl.email = E-mail
inic.lbl.contra = Senha
inic.btn.iniciarSesion = Entrar
inic.btn.registrar = Cadastrar-se

#Painel Cadastro
reg.lbl.titulo = CADASTRO
reg.lbl.nombre = Nome:
reg.lbl.apellido = Sobrenome:
reg.lbl.alias = Apelido (único e irrepetível):
reg.lbl.email = E-mail:
reg.lbl.fechaNac = Data de Nascimento (DD/MM/AAAA):
reg.lbl.contra = Senha:
reg.lbl.confirContra = Confirmar Senha:
reg.lbl.fotoPerfil = Clique para selecionar foto
reg.btn.registrar = Cadastrar
reg.btn.SeleccionarFoto = Alterar Foto
reg.btn.cancelar = Cancelar

#Painel Gênero
gen.lbl.titulo = Cadastrar-se como:
gen.lbl.hombre = Homem
gen.lbl.mujer = Mulher
gen.btn.volver = Voltar

#Perfis, para ambos os painéis
perfil.lbl.fotoPerf = Alterar Foto
perfil.lbl.nombre = Nome
perfil.lbl.apellido = Sobrenome
perfil.lbl.alias = Apelido
perfil.lbl.email = E-mail
perfil.lbl.estatura = Altura (cm):
perfil.lbl.edadMinima = Idade Mínima
perfil.lbl.edadMaxima = Idade Máxima
perfil.lbl.NuevaContraseña = Nova Senha
perfil.lbl.ConfirmarContraseña = Confirmar Senha
perfil.lbl.edad = Idade
perfil.lbl.visibilidad = Perfil visível para outros usuários
perfil.btn.actualizar = Atualizar
perfil.btn.foto = Alterar Foto
perfil.btn.cancelar = Cancelar
perfil.btn.cerrarSesion = Sair
perfil.btn.EliminarCuenta = Excluir Conta

#Painel Perfil Mulher
perfil.lbl.tituloMujer = PERFIL MULHER
perfil.lbl.divorcio = É divorciada?
perfil.lbl.estaIdeal = Altura Ideal (cm)

#Painel Perfil Homem
perfil.lbl.tituloHombre = PERFIL HOMEM
perfil.lbl.ingresos = Renda Mensal (R$):
perfil.lbl.mostrarDivorcio = Mostrar Mulheres Divorciadas

#Painel Principal Scroll
scroll.lbl.edad = Idade:
scroll.lbl.ingresos = Renda:
scroll.lbl.estatura = Altura:
scroll.lbl.divorciada = É divorciada?
scroll.lbl.smash = \u2764\uFE0F

#Painéis Info
panel.info.mensaje.InicioSesionExitoso = Login realizado com sucesso!
panel.info.nombre.InicioSesionExitoso = Login bem-sucedido
panel.info.mensagem.cuentaCreada = Conta criada
panel.info.nombre.cuentaCreada = Processo bem-sucedido
panel.info.mensaje.verificar = Verificação concluída
panel.info.nombre.verificar = O código inserido está correto
panel.info.mensaje.exito = Processo bem-sucedido
panel.info.nombre.exito = Perfil atualizado
panel.info.mensaje.cerrarSesion = Sessão encerrada
panel.info.nombre.cerrarSesion = Até a próxima!

#Painéis Erro
panel.error.mensaje.InicioSesionFallido = Senha ou e-mail incorretos
panel.error.nombre.InicioSesionFallido = Falha no login
panel.error.mensaje.correoInexistente = O e-mail não existe
panel.error.nombre.correoInexistente = Falha no cadastro
panel.error.mensagem.formatoInvalido = Formato de entrada inválido. Verifique os campos preenchidos.
panel.error.nombre.formatoInvalido = Erro de entrada
panel.error.mensaje.fechaNacimientoInvalida = A data de nascimento inserida é inválida.
panel.error.nombre.fechaNacimientoInvalida = Data inválida
panel.error.mensaje.textoInvalido = Texto inválido detectado em um dos campos.
panel.error.nombre.textoInvalido = Texto inválido
panel.error.mensaje.formatoCorreo = O formato do e-mail inserido é inválido.
panel.error.nombre.formatoCorreo = E-mail inválido
panel.error.mensaje.correoRepetido = O e-mail já está cadastrado. Use outro ou faça login.
panel.error.nombre.correoRepetido = E-mail já cadastrado
panel.error.mensaje.aliasExistente = O apelido já está em uso. Tente outro.
panel.error.nombre.aliasExistente = Apelido já em uso
panel.error.mensaje.contraseniasNoCoinciden = As senhas não coincidem. Verifique e tente novamente.
panel.error.nombre.contraseniasNoCoinciden = Senhas não coincidem
panel.error.mensaje.contraseniaDebil = A senha é muito fraca. Use pelo menos 8 caracteres, com maiúsculas, minúsculas e números.
panel.error.nombre.contraseniaDebil = Senha fraca
panel.error.mensaje.copiasImagen = Erro ao copiar a imagem:
panel.error.nombre.copiasImagen = Erro ao copiar a imagem
panel.error.mensaje.verificarInvalido = Erro na verificação
panel.error.nombre.verificarInvalido = Código incorreto
panel.error.mensaje.caracterInvalido = Apenas caracteres numéricos são permitidos
panel.error.nombre.caracterInvalido = Valor numérico inválido

#Painéis Aviso
panel.advertencia.mensaje.borrarCuenta = Esta ação não pode ser desfeita
panel.advertencia.nombre.borrarCuenta = Confirmar exclusão