#Panel Administrador
admin.btn.descPdf = Descargar PDF
admin.btn.elimUss = Desactivar cuenta

#Panel Codigo de Verificacion
cv.lbl.titulo = Ingrese el codigo de verificacion enviado a su correo
cv.btn.cerrarSesion = Cerrar Sesion
cv.btn.verificar = Verificar

#Panel Inicio de Sesion
inic.lbl.email = Email
inic.lbl.contra = Contraseña
inic.btn.iniciarSesion = Ingresar
inic.btn.registrar = Registrarse

#Panel Registro
reg.lbl.titulo = REGISTRO
reg.lbl.nombre = Nombre:
reg.lbl.apellido = Apellido:
reg.lbl.alias = Alias (único e irrepetible):
reg.lbl.email = Correo Electrónico:
reg.lbl.fechaNac = Fecha de Nacimiento (DD/MM/YYYY):
reg.lbl.contra = Contraseña:
reg.lbl.confirContra = Confirmar Contraseña:
reg.lbl.fotoPerfil = Click para seleccionar foto
reg.btn.registrar = Registrar
reg.btn.SeleccionarFoto = Cambiar Foto
reg.btn.cancelar = Cancelar

#Panel Genero
gen.lbl.titulo = Registrarse Como: 
gen.lbl.hombre = Hombre
gen.lbl.mujer = Mujer
gen.btn.volver = Volver

#Perfiles, para los dos paneles
perfil.lbl.fotoPerf = Cambiar Foto
perfil.lbl.nombre = Nombre
perfil.lbl.apellido = Apellido
perfil.lbl.alias = Alias
perfil.lbl.email = Correo
perfil.lbl.estatura = Estatura (cm):
perfil.lbl.edadMinima = Edad Minima
perfil.lbl.edadMaxima = Edad Maxima
perfil.lbl.NuevaContraseña = Nueva Contraseña
perfil.lbl.ConfirmarContraseña = Confirmar Contraseña
perfil.lbl.edadMaxima = Edad Maxima
perfil.lbl.edad = Edad
perfil.lbl.visibilidad = Perfil visible para otros usuarios
perfil.btn.actualizar = Actualizar
perfil.btn.foto = Cambiar Foto
perfil.btn.cancelar = Cancelar
perfil.btn.cerrarSesion = Cerrar Sesion
perfil.btn.EliminarCuenta = Eliminar Cuenta

#Panel Perfil Mujer
perfil.lbl.tituloMujer = PERFIL MUJER
perfil.lbl.divorcio = ¿Divorciada?
perfil.lbl.estaIdeal = Estatura Ideal (cm)

#Panel Perfil Hombre
perfil.lbl.tituloHombre = PERFIL HOMBRE
perfil.lbl.ingresos = Ingresos Mensuales ($):
perfil.lbl.mostrarDivorcio = Mostrar Mujeres Divorciadas

#Panel Principal Scroll
scroll.lbl.edad = Edad :
scroll.lbl.ingresos = Ingresos :
scroll.lbl.estatura = Estatura :
scroll.lbl.divorciada = ¿Es divorciada?
scroll.lbl.smash = \u2764\uFE0F