#Panel Administrador
admin.btn.descPdf = Descargar PDF
admin.btn.elimUss = Desactivar cuenta

#Panel Codigo de Verificacion
cv.lbl.titulo = Ingrese el codigo de verificacion enviado a su correo
cv.btn.cerrarSesion = Cerrar Sesion
cv.btn.verificar = Verificar

#Panel Inicio de Sesion
inic.lbl.email = Email
inic.lbl.contra = Contraseña
inic.btn.iniciarSesion = Ingresar
inic.btn.registrar = Registrarse

#Panel Perfil
perfil.lbl.titulo = Perfil
perfil.lbl.fotoPerf = Foto de Perfil (.jpg)
perfil.lbl.nombre = Nombres
perfil.lbl.apellido = Apellidos
perfil.lbl.alias = Alias
perfil.lbl.estatura = Estatura
perfil.lbl.visible = Visibilidad
perfil.lbl.estaIdeal = Estatura ideal
perfil.lbl.edadMinima = Edad minima
perfil.lbl.edadMaxima = Edad Maxima
perfil.lbl.ingresos = Ingresos mensuales
perfil.lbl.divorcio = Cantidad de Divorcios

#Panel Registro
reg.lbl.nombre = Nombre:
reg.lbl.apellido = Apellido:
reg.lbl.alias = Alias (único e irrepetible):
reg.lbl.email = Correo Electrónico:
reg.lbl.fechaNac = Fecha de Nacimiento (DD/MM/YYYY):
reg.lbl.contra = Contraseña:
reg.lbl.confirContra = Confirmar Contraseña:
reg.lbl.estatura = Estatura (cm):
reg.lbl.ingresosMensuales = Ingresos Mensuales ($):
reg.chk.divorciada = ¿Ha tenido divorcios?
reg.btn.registrar = Registrar
reg.btn.cancelar = Cancelar

#Panel Genero
gen.lbl.titulo = Registrarse como: 
gen.lbl.hombre = Hombre
gen.lbl.mujer = Mujer
gen.btn.volver = Volver