#Panel Administrador
admin.btn.descPdf = Descargar PDF
admin.btn.elimUss = Desactivar cuenta

#Panel Codigo de Verificacion
cv.lbl.titulo = Ingrese el codigo de verificacion enviado a su correo
cv.btn.cerrarSesion = Cerrar Sesion
cv.btn.verificar = Verificar

#Panel Inicio de Sesion
inic.lbl.email = Email
inic.lbl.contra = Contraseña
inic.btn.iniciarSesion = Ingresar
inic.btn.registrar = Registrarse

#Panel Registro
reg.lbl.nombre = Nombre:
reg.lbl.apellido = Apellido:
reg.lbl.alias = Alias (único e irrepetible):
reg.lbl.email = Correo Electrónico:
reg.lbl.fechaNac = Fecha de Nacimiento (DD/MM/YYYY):
reg.lbl.contra = Contraseña:
reg.lbl.confirContra = Confirmar Contraseña:
reg.lbl.estatura = Estatura (cm):
reg.lbl.ingresosMensuales = Ingresos Mensuales ($):
reg.chk.divorciada = ¿Ha tenido divorcios?
reg.btn.registrar = Registrar
reg.btn.cancelar = Cancelar

#Panel Genero
gen.lbl.titulo = Registrarse como: 
gen.lbl.hombre = Hombre
gen.lbl.mujer = Mujer
gen.btn.volver = Volver

#Perfiles, para los dos paneles
perfil.lbl.titulo = Perfil
perfil.lbl.fotoPerf = Cambiar foto
perfil.lbl.nombre = Nombre
perfil.lbl.apellido = Apellido
perfil.lbl.alias = Alias
perfil.lbl.email = Correo
perfil.lbl.estatura = Estatura
perfil.lbl.edadMinima = Edad minima
perfil.lbl.edadMaxima = Edad Maxima
perfil.lbl.visibilidad = Perfil visible para otros usuarios
perfil.btn.actualizar = Actualizar
perfil.btn.cancelar = Cancelar
perfil.btn.cerrarSesion = Cerrar Sesion

#Panel Perfil Mujer
perfil.lbl.divorcio = ¿Es divorciada?
perfil.lbl.estaIdeal = Estatura ideal

#Panel Perfil Hombre
perfil.lbl.ingresos = Ingresos mensuales
perfil.lbl.mostrarDivorcio = Mostrar mujeres divorciadas

#Panel Principal Scroll
scroll.lbl.edad = Edad :
scroll.lbl.ingresos = Ingresos :
scroll.lbl.estatura = Estatura :
scroll.lbl.divorciada = ¿Es divorciada?


