#Panel Administrador
admin.btn.descPdf = Download PDF
admin.btn.elimUss = Deactivate account

#Panel Codigo de Verificacion
cv.lbl.titulo = Enter the verification code sent to your email
cv.btn.cerrarSesion = Log Out
cv.btn.verificar = Verify

#Panel Inicio de Sesion
inic.lbl.email = Email
inic.lbl.contra = Password
inic.btn.iniciarSesion = Log In
inic.btn.registrar = Sign Up

#Panel Perfil
perfil.lbl.titulo = Profile
perfil.lbl.fotoPerf = Profile Picture (.jpg)
perfil.lbl.nombre = First Name(s)
perfil.lbl.apellido = Last Name(s)
perfil.lbl.alias = Alias
perfil.lbl.estatura = Height
perfil.lbl.visible = Visibility
perfil.lbl.estaIdeal = Ideal height
perfil.lbl.edadMinima = Minimum age
perfil.lbl.edadMaxima = Maximum age
perfil.lbl.ingresos = Monthly income
perfil.lbl.divorcio = Number of divorces

#Panel Registro
reg.lbl.nombre = Name:
reg.lbl.apellido = Last name:
reg.lbl.alias = Alias (unique and non-repeatable):
reg.lbl.email = Email address:
reg.lbl.fechaNac = Date of Birth (DD/MM/YYYY):
reg.lbl.contra = Password:
reg.lbl.confirContra = Confirm Password:
reg.lbl.estatura = Height (cm):
reg.lbl.ingresosMensuales = Monthly Income ($):
reg.chk.divorciada = Have you been divorced?
reg.btn.registrar = Register
reg.btn.cancelar = Cancel

#Panel Genero
gen.lbl.titulo = Register as: 
gen.lbl.hombre = Man
gen.lbl.mujer = Woman
gen.btn.volver = Back