#Panel Administrator
admin.btn.descPdf = Download PDF
admin.btn.elimUss = Deactivate Account

#Verification Code Panel
cv.lbl.titulo = Enter the verification code sent to your email
cv.btn.cerrarSesion = Log Out
cv.btn.verificar = Verify

#Login Panel
inic.lbl.email = Email
inic.lbl.contra = Password
inic.btn.iniciarSesion = Log In
inic.btn.registrar = Sign Up

#Registration Panel
reg.lbl.titulo = REGISTRATION
reg.lbl.nombre = First Name:
reg.lbl.apellido = Last Name:
reg.lbl.alias = Username (unique and non-repeatable):
reg.lbl.email = Email:
reg.lbl.fechaNac = Date of Birth (DD/MM/YYYY):
reg.lbl.contra = Password:
reg.lbl.confirContra = Confirm Password:
reg.lbl.fotoPerfil = Click to select profile picture
reg.btn.registrar = Register
reg.btn.SeleccionarFoto = Change Photo
reg.btn.cancelar = Cancel

#Gender Panel
gen.lbl.titulo = Register As:
gen.lbl.hombre = Male
gen.lbl.mujer = Female
gen.btn.volver = Back

#Profile (common for both panels)
perfil.lbl.fotoPerf = Change Photo
perfil.lbl.nombre = First Name
perfil.lbl.apellido = Last Name
perfil.lbl.alias = Username
perfil.lbl.email = Email
perfil.lbl.estatura = Height (cm):
perfil.lbl.edadMinima = Minimum Age
perfil.lbl.edadMaxima = Maximum Age
perfil.lbl.NuevaContraseña = New Password
perfil.lbl.ConfirmarContraseña = Confirm Password
perfil.lbl.edad = Age
perfil.lbl.visibilidad = Profile visible to other users
perfil.btn.actualizar = Update
perfil.btn.foto = Change Photo
perfil.btn.cancelar = Cancel
perfil.btn.cerrarSesion = Log Out
perfil.btn.EliminarCuenta = Delete Account

#Female Profile Panel
perfil.lbl.tituloMujer = FEMALE PROFILE
perfil.lbl.divorcio = Divorced?
perfil.lbl.estaIdeal = Ideal Height (cm)

#Male Profile Panel
perfil.lbl.tituloHombre = MALE PROFILE
perfil.lbl.ingresos = Monthly Income ($):
perfil.lbl.mostrarDivorcio = Show Divorced Women

#Main Scroll Panel
scroll.lbl.edad = Age:
scroll.lbl.ingresos = Income:
scroll.lbl.estatura = Height:
scroll.lbl.divorciada = Divorced?
scroll.lbl.smash = \u2764\uFE0F